# 移除质量评估模块的配置
model:
  input_dim: 64
  d_model: 256
  nhead: 8
  num_layers: 6
  dropout: 0.1
  max_seq_length: 10000
  use_quality_assessment: false  # 禁用质量评估

training:
  batch_size: 32
  num_epochs: 100
  learning_rate: 0.001
  weight_decay: 0.01
  warmup_steps: 1000
  gradient_clip: 1.0
  patience: 10

preprocessing:
  filter_range: [0.1, 50.0]
  denoise_threshold: 0.1
  segment_size: 1000
  overlap_ratio: 0.5
  adaptive_preprocessing: false  # 禁用自适应预处理

quality:
  enabled: false  # 禁用质量评估模块

optimization:
  quantization: true
  pruning_ratio: 0.3
  distillation: false
  mixed_precision: true 